# Bootstrap Configuration for Fresh NixOS Install
# 
# Copy this to /etc/nixos/configuration.nix on your fresh install
# This enables flakes so you can then use the flake-based config

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix  # This is auto-generated by the installer
  ];

  # Bootloader (adjust if you used different settings during install)
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";  # Change to your disk
  boot.loader.grub.useOSProber = true;

  # Or if you have UEFI:
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;

  # Hostname
  networking.hostName = "nixos";
  
  # Network
  networking.networkmanager.enable = true;

  # Timezone
  time.timeZone = "Africa/Tunis";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";

  # Enable flakes (REQUIRED!)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree packages (for NVIDIA drivers, VSCode, etc.)
  nixpkgs.config.allowUnfree = true;

  # Essential packages
  environment.systemPackages = with pkgs; [
    vim
    wget
    git        # Required to clone your dotfiles
    curl
    htop
  ];

  # Create your user
  users.users.dx07844 = {
    isNormalUser = true;
    description = "dx07844";
    extraGroups = [ "wheel" "networkmanager" ];
    # Set password with: passwd dx07844
  };

  # Enable sudo
  security.sudo.wheelNeedsPassword = true;

  # Enable SSH (optional)
  services.openssh.enable = true;

  # System version
  system.stateVersion = "25.11";  # Don't change this!
}
