# This file is auto-generated by nixos-generate-config
# You should replace this with your actual hardware-configuration.nix
# Run: sudo nixos-generate-config --show-hardware-config > hardware.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Placeholder - Replace with your actual hardware config
  # This should include:
  # - boot.initrd.availableKernelModules
  # - boot.initrd.kernelModules
  # - boot.kernelModules
  # - fileSystems
  # - swapDevices

  # From your important notes - Swap device
  swapDevices = [
    {
      device = "/dev/nvme0n1p6";
      # Optional: Swap optimization
      # priority = 100;  # Higher priority = used more often
      # discardPolicy = "once";  # TRIM support for SSD
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
